# Generated by Django 5.0.4 on 2024-06-05 07:29

import django.db.models.deletion
import turff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('game_image', models.ImageField(blank=True, null=True, upload_to=turff.models.getFileName)),
                ('status', models.BooleanField(default=False, help_text='0-show, 1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurfCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('turf_image', models.ImageField(blank=True, null=True, upload_to=turff.models.getFileName)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show, 1-Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('availability', models.BooleanField(default=True, help_text='True-Available, False-Not Available')),
                ('total_cost', models.FloatField()),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to='turff.gamecatagory')),
            ],
        ),
        migrations.CreateModel(
            name='Bookingss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_name', models.CharField(max_length=150)),
                ('game_description', models.TextField(max_length=500)),
                ('turf_name', models.CharField(max_length=150)),
                ('turf_description', models.TextField(max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='turff.gamecatagory')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='turff.turfcatagory')),
            ],
            options={
                'unique_together': {('turf', 'booking_date', 'time_slot')},
            },
        ),
    ]
